# Generated by Django 5.2.12 on 2026-03-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_pdu_control", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedpdu",
            name="last_metrics_fetched",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
