# Generated by Django 5.2.12 on 2026-03-23 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_pdu_control", "0002_managedpdu_last_metrics_fetched"),
    ]

    operations = [
        migrations.AddField(
            model_name="pduinlet",
            name="poleline_l1_current_a",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pduinlet",
            name="poleline_l2_current_a",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pduinlet",
            name="poleline_l3_current_a",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pduinlet",
            name="unbalanced_current_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pduinlet",
            name="unbalanced_ll_current_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pduinlet",
            name="unbalanced_ll_voltage_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PDUInletLinePair",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("inlet_number", models.PositiveIntegerField(default=1)),
                ("line_pair", models.CharField(max_length=4)),
                ("voltage_v", models.FloatField(blank=True, null=True)),
                ("current_a", models.FloatField(blank=True, null=True)),
                ("power_w", models.FloatField(blank=True, null=True)),
                ("apparent_power_va", models.FloatField(blank=True, null=True)),
                ("power_factor", models.FloatField(blank=True, null=True)),
                ("energy_wh", models.FloatField(blank=True, null=True)),
                ("last_updated_from_pdu", models.DateTimeField(blank=True, null=True)),
                (
                    "managed_pdu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inlet_linepairs",
                        to="netbox_pdu_control.managedpdu",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDU Inlet Line Pair",
                "verbose_name_plural": "PDU Inlet Line Pairs",
                "ordering": ("managed_pdu", "inlet_number", "line_pair"),
                "unique_together": {("managed_pdu", "inlet_number", "line_pair")},
            },
        ),
        migrations.CreateModel(
            name="PDUOverCurrentProtector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("ocp_id", models.CharField(max_length=10)),
                ("rating_current_a", models.FloatField(blank=True, null=True)),
                ("current_a", models.FloatField(blank=True, null=True)),
                ("poleline_l1_current_a", models.FloatField(blank=True, null=True)),
                ("poleline_l2_current_a", models.FloatField(blank=True, null=True)),
                ("poleline_l3_current_a", models.FloatField(blank=True, null=True)),
                ("tripped", models.BooleanField(blank=True, null=True)),
                ("last_updated_from_pdu", models.DateTimeField(blank=True, null=True)),
                (
                    "managed_pdu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocps",
                        to="netbox_pdu_control.managedpdu",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDU Over-Current Protector",
                "verbose_name_plural": "PDU Over-Current Protectors",
                "ordering": ("managed_pdu", "ocp_id"),
                "unique_together": {("managed_pdu", "ocp_id")},
            },
        ),
    ]
