# Generated by Django 6.0.6 on 2026-07-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_pdu_control', '0008_managedpdu_grafana_panel_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedpdu',
            name='api_password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
