# Generated by Django 6.0.6 on 2026-07-19 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0092_iprange_host_indexes'),
        ('netbox_pdu_control', '0009_alter_managedpdu_api_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedpdu',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_pdus', to='ipam.ipaddress'),
        ),
    ]
