# Generated by Django 6.0.6 on 2026-07-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_pdu_control', '0010_managedpdu_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedpdu',
            name='config_backup_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='managedpdu',
            name='last_config_saved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
